name: main-ci-target

on:
  pull_request_target:
    branches:
      - main

jobs:
  call-ci-test:
    uses: toddgiguere-sandbox/gha-common/blob/main/.github/workflows/ci-test.yml@main
    secrets: inherit
