name: main-ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  CI_Pipeline:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      THE_NAME: ${{ secrets.MY_NAME }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: hello
        run: |
          echo "IN WORKFLOW HELLO STEP"

      - name: step-two
        run: |
          echo "IN SECOND PULL STEP"

      - name: my-name-is
        run: |
          echo "Hello my name is: $THE_NAME"
