name: target-ci

on:
  pull_request_target:
    branches: [main]

jobs:
  CI_Target_Pipeline:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: hello-target
        run: |
          echo "IN TARGET WORKFLOW HELLO STEP"
          
      - name: target-step-2
        run: |
          echo "IN TARGET STEP TWO"
